### ISSUE TITLE
Possible `vars_files` collision?

### ISSUE THREAD

**Issue by Kenya-West** [geerlingguy/ansible-role-node_exporter#29]
Hello! I am relatively new to Ansible.

In my playbook: 

```yaml
---
- name: Install node_exporter
  hosts: local
  vars_files:
    - "{{ inventory_dir }}/vars/vars.yaml"
  become: true

  roles:
  - role: geerlingguy.node_exporter
```

I store `vars_files` in `"{{ inventory_dir }}/vars/vars.yaml"` path. The file is encrypted and instantly decrypted on any playbook run via `.vault_password.txt` file which contain password to decrypt vars,yaml file.

Using your role gives error: 

```log
fatal: [<SOME IP ADDRESS> -> localhost]: FAILED! => {
    "msg": "'root_password' is undefined"
}
```

I checked logs with `-vvv` option when launch the playbook, and found behaviour that is strange for me:

```log
TASK [geerlingguy.node_exporter : Configure latest version] **************************************
task path: /home/<SOME USER>/.ansible/roles/geerlingguy.node_exporter/tasks/main.yml:8
Read vars_file '{{ inventory_dir }}/vars/vars.yaml'
included: /home/<SOME USER>/.ansible/roles/geerlingguy.node_exporter/tasks/config-version.yaml for <SOME IP ADDRESS>
skipping vars_file '{{ inventory_dir }}/vars/vars.yaml' due to an undefined variable
Read vars_file '{{ inventory_dir }}/vars/vars.yaml'
skipping vars_file '{{ inventory_dir }}/vars/vars.yaml' due to an undefined variable

TASK [geerlingguy.node_exporter : Determine latest GitHub release (local)] ***********************
task path: /home/<SOME USER>/.ansible/roles/geerlingguy.node_exporter/tasks/config-version.yaml:2
fatal: [<SOME IP ADDRESS> -> localhost]: FAILED! => {
    "msg": "'root_password' is undefined"
}
```

While other playbooks catch variables file correctly, this one does not when using your role.

Where is the problem, exactly?

**Comment by Kenya-West** [comment]
All of sudden, the same error also happens with `cloudalchemy.node_exporter` role, on the same step:

```log
TASK [cloudalchemy.node_exporter : Get checksum list from github] **************************************************************************************************************************
task path: /home/kenyawest/.ansible/roles/cloudalchemy.node_exporter/tasks/preflight.yml:99
fatal: [192.168.31.203 -> localhost]: FAILED! => {
    "msg": "'root_password' is undefined"
}
```

And I do not understand what the cause. The error points to this YAML file:

```yaml 
- block:
    - name: Get checksum list from github
      set_fact:
        _checksums: "{{ lookup('url', 'https://github.com/prometheus/node_exporter/releases/download/v' + node_exporter_version + '/sha256sums.txt', wantlist=True) | list }}"
      run_once: true

    - name: "Get checksum for {{ go_arch }} architecture"
      set_fact:
        node_exporter_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ _checksums }}"
      when:
        - "('linux-' + go_arch + '.tar.gz') in item"
  delegate_to: localhost
  when: node_exporter_binary_local_dir | length == 0
```

which should not require `root_password` whatsoever as this variable is not defined in this role. It is defined in my `vars.yaml`. And why is it need to used here, when downloading something from GitHub?
