### ISSUE TITLE
Changing the node_exporter_options as no effect unless the package also changes and left over packages cause other issues

### ISSUE THREAD

**Issue by stecullum** [geerlingguy/ansible-role-node_exporter#33]
2 Issues..

Issue (1) ..Changing the node_options_does not get picked up unless we change the version 

Steps To Reproduce

+ Install version 1.6.1 of node-exporter
```
 - role: geerlingguy.node_exporter
      tags: node_exporter
      vars:
        node_exporter_version: 1.6.1
        node_exporter_options: '--collector.systemd"'
```
+ Change the node_exporter_options
```
 - role: geerlingguy.node_exporter
      tags: node_exporter
      vars:
        node_exporter_version: 1.6.1
        node_exporter_options: '--collector.textfile.directory=/var/lib/node_exporter/textfile_collector --collector.systemd"'
```

+ Rerun the playbook - the new options do not get pickedup

---
A workaround is to downgrade to 1.6.0 deploy to pick up the new node_exporter_options, and then redeploy 1.61.

However this leaves package 1.6.0 on disk in the /tmp folder so the redeployment is skipped leaving you with 1.6.0

+ Removing the downloaded packages from /tmp allows you to redeploy v1.6.1 again
