### ISSUE TITLE
Erro to run role in check mode

### ISSUE THREAD

**Issue by robsonjorgefernandez** [geerlingguy/ansible-role-node_exporter#37]
It's not possible to execute the role in `check mode`, because an error happens on task `Move node_exporter binary into place.`.

<details>
    <summary>check mode</summary>

```yaml
$ ansible-playbook all.yml --inventory inventory --diff --user user  --tags test --check

PLAY [STARTUP] ***

TASK [Gathering Facts] ***
ok: [localhost]

TASK [geerlingguy.node_exporter : DEBUG node_exporter_version_check] ***
ok: [localhost] =>
  msg:
    changed: false
    cmd:
    - /usr/local/bin/node_exporter
    - --version
    delta: null
    end: null
    failed: false
    msg: Command would have run if not in check mode
    rc: 0
    skipped: true
    start: null
    stderr: ''
    stderr_lines: []
    stdout: ''
    stdout_lines: []

TASK [geerlingguy.node_exporter : Move node_exporter binary into place.] ***
fatal: [localhost]: FAILED! => changed=false
  msg: Source /tmp/node_exporter-1.6.1.linux-amd64/node_exporter not found

PLAY RECAP ***
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0
```
</details>

<details>
<summary>dry-run</summary>

```yaml
$ ansible-playbook all.yml --inventory inventory --diff --user user --tags test

PLAY [STARTUP] ***

TASK [Gathering Facts] ***
ok: [localhost]

TASK [geerlingguy.node_exporter : Check current node_exporter version.] ***
ok: [localhost]

TASK [geerlingguy.node_exporter : DEBUG node_exporter_version_check] ***
ok: [localhost] =>
  msg:
    changed: false
    cmd:
    - /usr/local/bin/node_exporter
    - --version
    delta: '0:00:00.016327'
    end: '2024-09-16 21:48:19.542060'
    failed: false
    failed_when_result: false
    msg: ''
    rc: 0
    start: '2024-09-16 21:48:19.525733'
    stderr: ''
    stderr_lines: []
    stdout: |-
      node_exporter, version 1.6.1 (branch: HEAD, revision: 4a1b77600c1873a8233f3ffb55afcedbb63b8d84)
        build user:       root@586879db11e5
        build date:       20230717-12:10:52
        go version:       go1.20.6
        platform:         linux/amd64
        tags:             netgo osusergo static_build
    stdout_lines:
    - 'node_exporter, version 1.6.1 (branch: HEAD, revision: 4a1b77600c1873a8233f3ffb55afcedbb63b8d84)'
    - '  build user:       root@586879db11e5'
    - '  build date:       20230717-12:10:52'
    - '  go version:       go1.20.6'
    - '  platform:         linux/amd64'
    - '  tags:             netgo osusergo static_build'

TASK [geerlingguy.node_exporter : Create node_exporter user.] ***
ok: [localhost]

TASK [geerlingguy.node_exporter : Copy the node_exporter systemd unit file.] ***
ok: [localhost]

TASK [geerlingguy.node_exporter : Ensure node_exporter is running and enabled at boot.] ***
ok: [localhost]

TASK [geerlingguy.node_exporter : Verify node_exporter is responding to requests.] ***
ok: [localhost]

PLAY RECAP ***
localhost                  : ok=8    changed=0    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
```
</details>

I think we can change line [34](https://github.com/geerlingguy/ansible-role-node_exporter/blob/master/tasks/main.yml#L34) from:

```
or node_exporter_version_check.stdout | length == 0
```
to:
```
or node_exporter_version_check.stdout | length > 0
```
